networks:
  testpulse-net:

services:
  testpulseback:
    build: ./images/python
    container_name: testpulseback
    # restart: always
    environment:
      -  PYTHONDONTWRITEBYTECODE=1
      -  PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/pulse_back
    command: sh -c "pip3 install --no-cache-dir --default-timeout=100 -r requirements.txt && sleep 1  && python3 main.py"
    networks:
      - testpulse-net
    ports:
      - 7000:7000

  testfrontpulse:
    build: ./images/npm
    container_name: testfrontpulse
    # restart: always
    volumes:
      - ./pulse_front:/pulse
    networks:
      - testpulse-net
    ports:
      - 3020:3000
    stdin_open: true
    tty: true
    command: bash -c "npm install --force && npm i typescript --legacy-peer-deps && npm install --legacy-peer-deps && npm start"


  redis:
    image: redis:8.6.4-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
#    restart: always
    networks:
      - testpulse-net


  celery_currency:
    build: ./images/python
    container_name: celery_currency
    command: sh -c "pip3 install --no-cache-dir --default-timeout=100 -r requirements.txt && sleep 1 && python3 -m celery -A celery_app.celery_app worker"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - testpulse-net
    volumes:
      - ./backend:/pulse_back


  celery_beat:
    build: ./images/python
    container_name: celery_beat
    command: sh -c "pip3 install --no-cache-dir --default-timeout=100 -r requirements.txt && sleep 1 && python3 -m celery -A celery_app.celery_app beat"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - testpulse-net
    volumes:
      - ./backend:/pulse_back