"""link_stype

Revision ID: 0c5b9057231c
Revises: 749125a91e52
Create Date: 2026-05-26 12:06:21.666762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c5b9057231c"
down_revision: Union[str, None] = "749125a91e52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shop_link",
        "link",
        existing_type=sa.VARCHAR(length=400),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shop_link",
        "link",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=400),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
