"""add index

Revision ID: 27ef1ff43aec
Revises: 70bfd09b295d
Create Date: 2026-06-12 11:48:09.888685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27ef1ff43aec"
down_revision: Union[str, None] = "70bfd09b295d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_day_price_currency_id"), "day_price", ["currency_id"], unique=False
    )
    op.create_index(op.f("ix_day_price_date"), "day_price", ["date"], unique=False)
    op.create_index(
        op.f("ix_day_price_shop_link_id"), "day_price", ["shop_link_id"], unique=False
    )
    op.create_index(
        op.f("ix_exchange_rate_base_currency_id"),
        "exchange_rate",
        ["base_currency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_rate_currency_id"),
        "exchange_rate",
        ["currency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shop_link_shop_id"), "shop_link", ["shop_id"], unique=False
    )
    op.create_index(op.f("ix_shop_link_tv_id"), "shop_link", ["tv_id"], unique=False)
    op.drop_constraint("tv_name_key", "tv", type_="unique")
    op.create_index(op.f("ix_tv_brand_id"), "tv", ["brand_id"], unique=False)
    op.create_index(op.f("ix_tv_diagonal"), "tv", ["diagonal"], unique=False)
    op.create_index(
        op.f("ix_tv_matrix_type_id"), "tv", ["matrix_type_id"], unique=False
    )
    op.create_index(op.f("ix_tv_name"), "tv", ["name"], unique=True)
    op.create_index(op.f("ix_tv_os_id"), "tv", ["os_id"], unique=False)
    op.create_index(op.f("ix_tv_refresh_rate"), "tv", ["refresh_rate"], unique=False)
    op.create_index(
        op.f("ix_tv_screen_resolution_id"), "tv", ["screen_resolution_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tv_screen_resolution_id"), table_name="tv")
    op.drop_index(op.f("ix_tv_refresh_rate"), table_name="tv")
    op.drop_index(op.f("ix_tv_os_id"), table_name="tv")
    op.drop_index(op.f("ix_tv_name"), table_name="tv")
    op.drop_index(op.f("ix_tv_matrix_type_id"), table_name="tv")
    op.drop_index(op.f("ix_tv_diagonal"), table_name="tv")
    op.drop_index(op.f("ix_tv_brand_id"), table_name="tv")
    op.create_unique_constraint(
        "tv_name_key", "tv", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_shop_link_tv_id"), table_name="shop_link")
    op.drop_index(op.f("ix_shop_link_shop_id"), table_name="shop_link")
    op.drop_index(op.f("ix_exchange_rate_currency_id"), table_name="exchange_rate")
    op.drop_index(op.f("ix_exchange_rate_base_currency_id"), table_name="exchange_rate")
    op.drop_index(op.f("ix_day_price_shop_link_id"), table_name="day_price")
    op.drop_index(op.f("ix_day_price_date"), table_name="day_price")
    op.drop_index(op.f("ix_day_price_currency_id"), table_name="day_price")
    # ### end Alembic commands ###
