"""add rate scale

Revision ID: 2b03098eab54
Revises: 31487095b729
Create Date: 2026-05-25 14:10:36.932818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b03098eab54"
down_revision: Union[str, None] = "31487095b729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exchange_rate",
        sa.Column("scale", sa.Integer(), server_default="1", nullable=False),
    )
    op.alter_column(
        "tv",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tv",
        "name",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("exchange_rate", "scale")
    # ### end Alembic commands ###
