"""tv_name_str_text

Revision ID: 70bfd09b295d
Revises: 82ee9c198bc0
Create Date: 2026-05-30 20:18:56.811375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70bfd09b295d"
down_revision: Union[str, None] = "82ee9c198bc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tv",
        "name",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tv",
        "name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
