"""link_size

Revision ID: 749125a91e52
Revises: 2b03098eab54
Create Date: 2026-05-26 12:02:41.499930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "749125a91e52"
down_revision: Union[str, None] = "2b03098eab54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shop_link",
        "link",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=400),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shop_link",
        "link",
        existing_type=sa.String(length=400),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
