"""cur_id

Revision ID: 0ebcb39125cf
Revises: c8f2912b55b5
Create Date: 2026-06-23 10:03:01.832636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ebcb39125cf"
down_revision: Union[str, None] = "c8f2912b55b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency", sa.Column("cur_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currency", "cur_id")
    # ### end Alembic commands ###
