FROM python:3.13.13-alpine3.23
#RUN apt-get update && \
#    apt-get -y install curl && \
#    apt-get -y install gnupg && \
#    apt-get -y install wget && \
#    apt-get -y install gcc
WORKDIR /pulse_back
# CMD ["python3 src/main.py"]
